// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/password-reset/:token": {
    params: {
      "token": string;
    };
  };
  "/auth/callback": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/verify-email" | "/password-reset/:token" | "/auth/callback";
  };
  "routes/pages/EditorPage/EditorPage.tsx": {
    id: "routes/pages/EditorPage/EditorPage";
    page: "/";
  };
  "routes/pages/Auth/Login.tsx": {
    id: "routes/pages/Auth/Login";
    page: "/login";
  };
  "routes/pages/Auth/Register.tsx": {
    id: "routes/pages/Auth/Register";
    page: "/register";
  };
  "routes/pages/Auth/EmailVerif.tsx": {
    id: "routes/pages/Auth/EmailVerif";
    page: "/verify-email";
  };
  "routes/pages/Auth/PasswordReset.tsx": {
    id: "routes/pages/Auth/PasswordReset";
    page: "/password-reset/:token";
  };
  "routes/pages/Auth/Callback.tsx": {
    id: "routes/pages/Auth/Callback";
    page: "/auth/callback";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/pages/EditorPage/EditorPage": typeof import("./app/routes/pages/EditorPage/EditorPage.tsx");
  "routes/pages/Auth/Login": typeof import("./app/routes/pages/Auth/Login.tsx");
  "routes/pages/Auth/Register": typeof import("./app/routes/pages/Auth/Register.tsx");
  "routes/pages/Auth/EmailVerif": typeof import("./app/routes/pages/Auth/EmailVerif.tsx");
  "routes/pages/Auth/PasswordReset": typeof import("./app/routes/pages/Auth/PasswordReset.tsx");
  "routes/pages/Auth/Callback": typeof import("./app/routes/pages/Auth/Callback.tsx");
};